### ISSUE TITLE
Trademark violation

### ISSUE THREAD

**Issue by yroc92** [WedgeServer/wedge#2]
The word "Caddy" in the context of software is under a pending trademark application. By using the name Caddy in your repo, along with the associated logos, you're in violation of this trademark. Please remove all such references :)

**Comment by lol768** [comment]
> The word "Caddy" in the context of software is under a pending trademark application

So it's not a registered trademark?

> By using the name Caddy in your repo, along with the associated logos, you're in violation of this trademark. Please remove all such references :)

See issue #1 - this is planned 😃

**Comment by yroc92** [comment]
Technically, there is an implicit trademark because of the continued use and recognition of the brand over the years, and it is legally enforceable. But we have also submitted a formal trademark request as well, which is pending. Just FYI, we have no problem with anyone forking Caddy. We enjoy open source!

Can I ask what your use case for Caddy is?

**Comment by SirCmpwn** [comment]
Pretty disingenous for you to refer to yourself as a member of Caddy's "we" when so far as I can tell you're not involved: https://github.com/mholt/caddy/graphs/contributors

**Comment by yroc92** [comment]
@SirCmpwn I'm part owner of Light Code Labs, the legal entity that filed for the trademark.

**Comment by SirCmpwn** [comment]
I see. Well, in any case, be patient, and maybe also try contributing to your own web server?

**Comment by yroc92** [comment]
You got it 👍

**Comment by lol768** [comment]
Thanks for clarifying your involvement, @yroc92. It's great to hear you value open source!

In the United Kingdom, trademark violation requires a mark to be used "in the course of trade". I have no plans to make commercial use of this project in any form whatsoever (including but not limited to adding sponsor headers to HTTP responses and then charging for them to be removed).

With that said, I will be removing references to Caddy throughout the codebase as you have requested, though the primary benefit here in my opinion is reducing user confusion and ensuring users do not go seeking support from the wrong place.

**Comment by gonzopancho** [comment]
@lol768 

As long as you're dolling out legal advice on the Internet, you might well quote the other relevant section of the Trade Marks Act of 1994.

> A person may also infringe a registered trade mark where the sign is similar and the goods or services are similar to those for which the mark is registered and there is a likelihood of confusion on the part of the public as a result

See: section 10(2)(b) http://euipo.europa.eu/pdf/mark/nl_uk_1_en.pdf

I am not a lawyer, but I am somewhat versed in trademark law.   Your dependence on "commercial use" may be unsupportable, but talk to an attorney for legal advice.

LCL are actually doing the right thing to defend their mark by providing notice.

**Comment by lol768** [comment]
Thanks for contributing your expertise @gonzopancho :)

The start of section 10 (2) states:

>A person infringes a registered trade mark if he uses **in the course of trade** a sign where
because:

Your quoted section is indented underneath the above.

----------

This is moot however, because I have already committed to change the name.

**Comment by mholt** [comment]
Just wanted to comment here and say thank you for the respect and the professional tone of the discussion. I was in class most of this morning and so Cory and I haven't had a chance to coordinate. I stand by Cory's choice to bring up the issue and I think this discussion was a good one to have.

As you know, per the Apache license, forks are required to maintain copyright notices and give credit to the original project, etc, so the name Caddy *should* be used somewhere in a visible place, I think the main concern was with the logo being used prominently. But the README was quickly updated, which we appreciate.

We're glad there are people who value Caddy enough and feel strongly enough about it to fork it with their own changes. Hopefully this won't result in a splintered effort to make the Web better and safer, instead we look forward to mutually benefitting somehow.

**Comment by lol768** [comment]
Hey @mholt,

Great to see you weigh in here and thanks for the conversation on HackerNews. It was useful to discuss things, even if I do completely disagree with the direction in which you're going with this.

> As you know, per the Apache license, forks are required to maintain copyright notices and give credit to the original project, etc, so the name Caddy should be used somewhere in a visible place, I think the main concern was with the logo being used prominently. But the README was quickly updated, which we appreciate.

Apologies for that. GitHub's fork feature is great at duplicating everything, so the README was misleading for a while. I'm happy to mention that this is a fork of Caddy in the README as required by the Apache license and will look at making this more obvious if it's not already apparent.

Are you happy for me to mention that Caddy has a paid support offering and link https://caddyserver.com/pricing in the README for users seeking commercial support? If it wasn't already clear, my intentions are to remove the code I disagree with for people who want to use Caddy _personally_ (though I'm also of the opinion that the binaries I will be distributing here shouldn't be limited). I'm not here to try and sell a commercial support offering.

> We're glad there are people who value Caddy enough and feel strongly enough about it to fork it with their own changes. Hopefully this won't result in a splintered effort to make the Web better and safer, instead we look forward to mutually benefitting somehow.

As long as you're intending on a) leaving the trademark issue alone and b) keeping the upstream repository open source (and licensed under an appropriate free software license), I'm happy to contribute any relevant fixes/improvements upstream and include the link I mentioned above.

It is unfortunate that at present you don't seem open to reversing your decision to introduce advertising into Caddy. I still dislike what you're doing with the binaries, but I don't dislike it enough to motivate me to continue maintaining this repository - it's really the header I have a problem with.

Caddy is an excellent piece of software, I would really urge you to read through the HackerNews thread again at some point and reconsider if this is the approach you want to take. Neither of us want to see more fragmentation here, I think.

Cheers,
Adam

**Comment by mholt** [comment]
> Apologies for that. GitHub's fork feature is great at duplicating everything, so the README was misleading for a while. I'm happy to mention that this is a fork of Caddy in the README as required by the Apache license and will look at making this more obvious if it's not already apparent.

Yeah, no problem. We were very quick to jump in here after the fork; I realize from my own experience that this isn't enough time. It was a very busy, fast-moving morning. :)

> Are you happy for me to mention that Caddy has a paid support offering and link https://caddyserver.com/pricing in the README for users seeking commercial support? If it wasn't already clear, my intentions are to remove the code I disagree with for people who want to use Caddy personally (though I'm also of the opinion that the binaries I will be distributing here shouldn't be limited). I'm not here to try and sell a commercial support offering.

Sure, you may certainly do that.

> As long as you're intending on a) leaving the trademark issue alone and b) keeping the upstream repository open source (and licensed under an appropriate free software license), I'm happy to contribute any relevant fixes/improvements upstream and include the link I mentioned above.

Sounds good to me. The use of our logo at the top of your fork was quickly resolved anyway.

> It is unfortunate that at present you don't seem open to reversing your decision to introduce advertising into Caddy.

Well, it's only been 7 hours. :) Let's give it some time and see how things are when the dust settles. Believe me, it's not a decision I took lightly.

> Caddy is an excellent piece of software, I would really urge you to read through the HackerNews thread again at some point and reconsider if this is the approach you want to take. Neither of us want to see more fragmentation here, I think.

Thanks - yes, I agree. (Frankly I'm not too convinced by the HN arguments -- as usual -- except for recognizing the fact that our pricing can be out of reach for small, bootstrapping startups; we encourage them to contact us about special pricing in the meantime.)

**Comment by SirCmpwn** [comment]
>Frankly I'm not too convinced by the HN arguments

My main concern, which you probably saw, is that your website is deceptive. Nothing's wrong with getting paid for your work, but your website is designed in bad faith.

**Comment by mholt** [comment]
@SirCmpwn 

> My main concern, which you probably saw, is that your website is deceptive. Nothing's wrong with getting paid for your work, but your website is designed in bad faith.

Come again&mdash;what's deceptive?

**Comment by SirCmpwn** [comment]
I wrote about it [on HN](https://news.ycombinator.com/item?id=15238969).

**Comment by joshmanders** [comment]
I'm confused at what this fork offers that Caddy doesn't... Is it the code that shows the headers that you removed all that's stopping you from using Caddy? 

You do realize that you can compile Caddy yourself without those headers in it, without forking it and maintaining a whole new project, right?

From my point of view people are upset by 2 things. 1: They can't get pre-compiled binaries without the header and 2: if they can, they have to pay for it.

If anything, this fork adds MORE work on you than what Caddy says to do to use it free of charge without the headers.

**Comment by nqzero** [comment]
this trademark claim appears to be a false claim. the original caddy is hosted on github, and per the [github faq](https://help.github.com/articles/licensing-a-repository/):

> Note: If you publish your source code in a public repository on GitHub, according to the Terms of Service, other GitHub users have the right to view and fork your repository within the GitHub site. If you have already created a public repository and no longer want users to have access to it, you can make your repository private. When you convert a public repository to a private repository, existing forks or local copies created by other users will still exist. For more information, see "Making a public repository private."

i realize that you've already complied with the request, but based on this, it appears that the caddy team are not acting in good faith

**Comment by mholt** [comment]
> not acting in good faith

A misunderstanding or miscommunication is a far cry from "not in good faith". I'm gonna stand firm here and re-assert that our actions are in good faith.

The misunderstandings about the use of the logo have been resolved.

**Comment by SirCmpwn** [comment]
The bad faith part comes in because so far as I can tell you are *deliberately* misleading users.

**Comment by lol768** [comment]
> I'm confused at what this fork offers that Caddy doesn't... Is it the code that shows the headers that you removed all that's stopping you from using Caddy?

Removal of adware and binaries that can be freely distributed and are not subject to an EULA.

> You do realize that you can compile Caddy yourself without those headers in it, without forking it and maintaining a whole new project, right?

Yes, I didn't overlook that :)

> From my point of view people are upset by 2 things. 1: They can't get pre-compiled binaries without the header and 2: if they can, they have to pay for it.
> If anything, this fork adds MORE work on you than what Caddy says to do to use it free of charge without the headers.

From my point of view (and from reading HackerNews) people are upset about the ads embedded in the webserver and served to the visitors. They're also upset about how the binaries are licensed.

The fork is absolutely more work for me. The point is that I care enough about this that I'm willing to create the fork, remove the code I disagree with, cross-compile it and then make free (as in freedom) binaries available to everyone - including those who may not be technically adept enough to set up their own golang workspace and compile it themselves.

**Comment by pepa65** [comment]
I think forking on Github does not require removing any reference to the project you forked from.

**Comment by joshmanders** [comment]
> The fork is absolutely more work for me. The point is that I care enough about this that I'm willing to create the fork, remove the code I disagree with, cross-compile it and then make free (as in freedom) binaries available to everyone - including those who may not be technically adept enough to set up their own golang workspace and compile it themselves.

Until you run into the issues that Caddy had where it actually costs a lot of money to maintain and use the infra to do such things in a way that is helpful.

Then we're right back where we started, you doing something in a way to help make money to support that stuff, everyone getting upset, and forking a forked project that was forked from another fork that forked from a project that started such tactics to help.

The circle of open sores, I like to call it.

**Comment by SirCmpwn** [comment]
I find it highly unlikely that's going to happen. I have infrastructure, if you ever need somewhere to host builds or tooling like caddy offers, reach out and I'll share it for free.

**Comment by dougpagani** [comment]
5 years later, fair to say this fork was created out of spite with no intentions to sustain it 😂

Grandstanding sure is cheap.

**Comment by ddevault** [comment]
They stopped the bad faith behavior upstream so there's no longer any reason for this fork to exist. Imagine sticking up for a company that you have nothing to do with when they go around being a trademark bully. You sure showed that petty FOSS volunteer the error of their defiance towards the honorable corporate entity!

**Comment by joshmanders** [comment]
> They stopped the bad faith behavior upstream so there's no longer any reason for this fork to exist. Imagine sticking up for a company that you have nothing to do with when they go around being a trademark bully. You sure showed that petty FOSS volunteer the error of their defiance towards the honorable corporate entity!

Imagine thinking that a solo developer trying to make a living from his work is some trademark bully and evil corporate entity, just because they have an LLC and premium support plans.

**Comment by ddevault** [comment]
Trying to make a living does not make it okay to be deceptive and misleading or to threaten others. There are plenty of ways to make a living without being deceptive, especially for a talented programmer. Get your moral compass re-calibrated.

**Comment by lol768** [comment]
> 5 years later, fair to say this fork was created out of spite with no intentions to sustain it 😂

Bit of a strange thing to do, resurrecting an issue 5 years on to post .. that.

However - as Drew has already pointed out, the fork became obsolete as soon as upstream 180'd and dropped the tacky, baked-in ads. I'm glad no significant fork maintenance / investment in a build system was required in the end, given Matt took the sensible decision to merge the PR to remove the header (which had been added without even consulting his sponsors, putting some of them in an incredibly awkward position amongst the negative reception).

Most of us have now moved on. I am glad Caddy has a more sustainable funding position - I see this debacle as an illustration of the power of open source (and forking) providing a "checks and balances" mechanism when it comes to undesirable moves from upstream.
